const defaults = {
  income: 128000,
  categories: [
    {id:'food',type:'expense',emoji:'🛒',name:'Продукты',color:'#7664dd'}, {id:'transport',type:'expense',emoji:'🚗',name:'Транспорт',color:'#52b6d2'}, {id:'cafe',type:'expense',emoji:'🍔',name:'Кафе',color:'#ed9b55'}, {id:'fun',type:'expense',emoji:'🎮',name:'Развлечения',color:'#ed7282'},
    {id:'salary',type:'income',emoji:'💼',name:'Зарплата',color:'#1aaa85'}, {id:'freelance',type:'income',emoji:'💻',name:'Фриланс',color:'#1aaa85'}, {id:'investment',type:'income',emoji:'📈',name:'Инвестиции',color:'#1aaa85'}
  ],
  goals: [{id:1,emoji:'🏍️',title:'Мотоцикл',description:'Мотоцикл для поездок за город',target:600000,current:180000,date:'2027-06-01'}, {id:2,emoji:'🌊',title:'Отпуск в Японии',description:'Весеннее путешествие',target:240000,current:4000,date:'2027-04-01'}],
  transactions: [{id:1,type:'expense',category:'food',amount:3240,comment:'Продукты на неделю',date:'2026-08-24',time:'11:30'}, {id:2,type:'expense',category:'transport',amount:680,comment:'Такси',date:'2026-08-23',time:'20:10'}, {id:3,type:'income',category:'salary',amount:120000,comment:'Август',date:'2026-08-20',time:'09:00'}, {id:4,type:'expense',category:'cafe',amount:1240,comment:'Ужин с друзьями',date:'2026-08-19',time:'19:40'}, {id:5,type:'income',category:'freelance',amount:8000,comment:'Проект',date:'2026-08-15',time:'14:20'}]
};
const $ = s => document.querySelector(s);
const storageKey = window.TG?.storageKey || 'kopilka-data';
let state = JSON.parse(localStorage.getItem(storageKey) || 'null') || structuredClone(defaults);
let selectedPlanMonth = monthKey(new Date()), categoryTab = 'expense', remoteReady = false, syncTimer;
const money = n => new Intl.NumberFormat('ru-RU').format(Math.round(n || 0)) + ' ₽';
const haptic = () => window.Telegram?.WebApp?.HapticFeedback?.notificationOccurred?.('success');
function monthKey(value) { const d = value instanceof Date ? value : new Date(value + 'T12:00:00'); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; }
function dateLabel(value) { return value ? `до ${new Date(value+'T12:00:00').toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}` : 'Без срока'; }
function nowFields() { const now=new Date(); return {date:now.toISOString().slice(0,10),time:now.toTimeString().slice(0,5)}; }
function getCategory(id) { return state.categories.find(c => c.id === id); }
function getGoal(id) { return state.goals.find(g => String(g.id) === String(id)); }
function activeCategories(type) { return state.categories.filter(c => c.type === type && !c.archived); }
function getPlan(key=selectedPlanMonth, create=true) { if (!state.plans[key] && create) state.plans[key] = { incomeTarget: 0, budgets: {}, spent: {} }; return state.plans[key]; }
function planCategories() { const plan=getPlan(); return activeCategories('expense').filter(c => Object.hasOwn(plan.budgets,c.id)); }
function expenses() { return activeCategories('expense').reduce((sum,c)=>sum+(c.spent||0),0); }
function goalNet() { return state.transactions.filter(t=>t.type==='goal_deposit'||t.type==='goal_withdrawal').reduce((sum,t)=>sum+(t.type==='goal_deposit'?t.amount:-t.amount),0); }
function availableNow() { return state.income - expenses() - goalNet(); }
function allocated() { return Object.values(getPlan().budgets).reduce((sum,n)=>sum+Number(n||0),0); }
function reserved() { const plan=getPlan(); return Object.keys(plan.budgets).reduce((sum,id)=>sum+Math.max(0,Number(plan.budgets[id]||0)-Number(plan.spent[id]||0)),0); }
function normalizeState() {
  state.income ??= 0; state.categories ??=[]; state.goals ??=[]; state.transactions ??=[]; state.plans ??={};
  state.categories.forEach(c=>{ c.type ??= ['salary','freelance','investment'].includes(c.id)?'income':'expense'; });
  defaults.categories.filter(c=>c.type==='income'&&!state.categories.some(x=>x.id===c.id)).forEach(c=>state.categories.push(structuredClone(c)));
  const current=monthKey(new Date());
  if (!state.plans[current]) { const legacy={incomeTarget:state.planIncome||state.income,budgets:{},spent:{}}; state.categories.filter(c=>c.type==='expense'&&c.inPlan!==false&&Number(c.plan)>0).forEach(c=>{legacy.budgets[c.id]=Number(c.plan)}); state.plans[current]=legacy; }
  state.transactions.forEach(t=>{t.time??='';});
  rebuildLedgerTotals();
}
function rebuildLedgerTotals(){
  // History is the source of truth. Old versions stored category totals separately,
  // which left phantom expenses after a history record was deleted.
  state.income=0;
  state.categories.filter(c=>c.type==='expense').forEach(c=>c.spent=0);
  Object.values(state.plans).forEach(plan=>plan.spent={});
  state.transactions.forEach(t=>{
    const amount=Number(t.amount||0);
    if(t.type==='income') state.income+=amount;
    if(t.type==='expense'){
      const category=getCategory(t.category); if(category)category.spent+=amount;
      const plan=getPlan(monthKey(t.date)); plan.spent[t.category]=(plan.spent[t.category]||0)+amount;
    }
  });
}
normalizeState();
function setSyncStatus(message='', error=false) { const el=$('#syncStatus'); if(!el)return; el.textContent=message; el.classList.toggle('error',error); }
const canSync=()=>Boolean(window.TG?.isTelegram&&window.TG.webApp?.initData);
async function saveRemote(){try{const response=await fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json','authorization':`tma ${window.TG.webApp.initData}`},body:JSON.stringify({state})});if(!response.ok)throw Error();setSyncStatus('Сохранено');setTimeout(()=>setSyncStatus(),1800)}catch{setSyncStatus('Нет синхронизации',true)}}
function save(){localStorage.setItem(storageKey,JSON.stringify(state));if(remoteReady&&canSync()){clearTimeout(syncTimer);syncTimer=setTimeout(saveRemote,500)}}
async function hydrateRemote(){if(!canSync())return;setSyncStatus('Загрузка…');try{const response=await fetch('/api/state',{headers:{authorization:`tma ${window.TG.webApp.initData}`}});if(!response.ok)throw Error();const payload=await response.json();if(payload.state?.categories){state=payload.state;normalizeState();render()}remoteReady=true;save();setSyncStatus('Синхронизировано');setTimeout(()=>setSyncStatus(),1800)}catch{remoteReady=true;setSyncStatus('Нет синхронизации',true)}}
function applyOperation(t, direction) {
  const amount=Number(t.amount||0)*direction;
  if(t.type==='income') state.income += amount;
  if(t.type==='expense') { const c=getCategory(t.category); if(c)c.spent=Math.max(0,Number(c.spent||0)+amount); const plan=getPlan(monthKey(t.date)); plan.spent[t.category]=Math.max(0,Number(plan.spent[t.category]||0)+amount); }
  if(t.type==='goal_deposit'||t.type==='goal_withdrawal') { const goal=getGoal(t.goalId); const multiplier=t.type==='goal_deposit'?1:-1; if(goal)goal.current=Math.max(0,Number(goal.current||0)+amount*multiplier); }
}
function operationTarget(t){ if(t.type==='goal_deposit'||t.type==='goal_withdrawal'){const g=getGoal(t.goalId);return {emoji:g?.emoji||'🎯',name:g?.title||'Цель'}} const c=getCategory(t.category);return {emoji:c?.emoji||'💳',name:c?.name||'Операция'}; }
function transactionHtml(t){const target=operationTarget(t), sign=['income','goal_withdrawal'].includes(t.type)?'+':'−';const kind=t.type==='income'?'income':t.type==='goal_withdrawal'?'income':'expense';const label=t.type==='goal_deposit'?'Пополнение цели':t.type==='goal_withdrawal'?'Снятие с цели':target.name;return `<div class="transaction"><span class="transaction-icon">${target.emoji}</span><div><div class="transaction-title">${t.comment||label}</div><div class="transaction-meta">${label} · ${new Date(t.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}${t.time?' · '+t.time:''}</div></div><span class="transaction-amount ${kind}">${sign}${money(t.amount)}</span><button class="edit-transaction" data-edit-operation="${t.id}" aria-label="Изменить операцию">✎</button><button class="delete-transaction" data-delete-transaction="${t.id}" aria-label="Удалить операцию">×</button></div>`}
function render(){
  const available=availableNow(), plan=getPlan(), assigned=reserved(), unallocated=available-assigned, pct=available?Math.max(0,Math.round(assigned/available*100)):0;
  $('#balanceValue').textContent=money(available);$('#incomeSmall').textContent=money(state.income);$('#expenseSmall').textContent=money(expenses());$('#allocatedValue').innerHTML=`${money(assigned)} <small>из ${money(available)}</small>`;$('#unallocatedValue').textContent=money(unallocated);$('#planUnallocated').textContent=money(unallocated);$('#budgetPercent').textContent=pct+'%';$('#budgetRing').style.background=`conic-gradient(var(--purple) ${pct}%,#ebeaf5 0)`;$('.summary-progress span').style.width=Math.min(pct,100)+'%';
  const [year,month]=selectedPlanMonth.split('-');$('#planMonthLabel').textContent=new Date(Number(year),Number(month)-1,1).toLocaleDateString('ru-RU',{month:'long',year:'numeric'}).toUpperCase();
  $('#recentTransactions').innerHTML=state.transactions.slice(0,3).map(transactionHtml).join('');$('#historyList').innerHTML=state.transactions.map((t,i)=>`${i===0||t.date!==state.transactions[i-1].date?`<div class="history-date">${new Date(t.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</div>`:''}${transactionHtml(t)}`).join('');
  $('#budgetList').innerHTML=planCategories().map(c=>{const budget=Number(plan.budgets[c.id]||0),spent=Number(plan.spent[c.id]||0),percent=budget?Math.round(spent/budget*100):0,over=spent>budget;return `<article class="budget-item ${over?'over':''}" data-edit-budget="${c.id}"><div class="budget-row"><span class="budget-emoji">${c.emoji}</span><div><div class="budget-name">${c.name}</div><div class="budget-numbers">Потрачено ${money(spent)} из ${money(budget)}</div></div><div class="budget-remain">${money(budget-spent)}<small>${over?'Перерасход':percent+'% использовано'}</small></div></div><div class="budget-bar"><span style="width:${Math.min(percent,100)}%;background:${c.color||''}"></span></div></article>`}).join('')||'<p class="hint">В этом месяце ещё нет распределённых категорий.</p>';
  const total=state.goals.reduce((s,g)=>s+Number(g.current||0),0),target=state.goals.reduce((s,g)=>s+Number(g.target||0),0);$('#goalsTotal').textContent=money(total);$('.goals-total p').textContent=`Вы уже на ${target?Math.round(total/target*100):0}% пути к своим целям`;$('#goalsList').innerHTML=state.goals.map(g=>{const p=Math.min(100,Math.round(g.current/g.target*100));return `<article class="goal-card" data-edit-goal="${g.id}"><div class="goal-card-top"><div class="goal-title">${g.emoji||'🎯'} ${g.title}</div><div class="goal-amount">${p}%</div></div><div class="goal-info">${g.description?g.description+' · ':''}${money(g.current)} из ${money(g.target)}</div><div class="goal-info">${dateLabel(g.date)}</div><div class="goal-progress"><span style="width:${p}%"></span></div><div class="goal-actions"><button data-goal-move="deposit" data-goal-id="${g.id}">Пополнить</button><button data-goal-move="withdraw" data-goal-id="${g.id}">Снять</button></div></article>`}).join('');
  const top=[...activeCategories('expense')].sort((a,b)=>(b.spent||0)-(a.spent||0))[0];$('#analyticsExpense').textContent=money(expenses());$('#topCategory').textContent=top?`${top.emoji} ${top.name}`:'—';$('#topCategoryAmount').textContent=top?money(top.spent):'0 ₽';$('#avgExpense').textContent=money(expenses()/27);$('#analyticsBudget').innerHTML=planCategories().filter(c=>plan.budgets[c.id]).map(c=>`<div class="analytics-row"><span>${c.emoji}</span><div><b>${c.name}</b><div class="budget-bar"><span style="width:${Math.min(100,plan.spent[c.id]/plan.budgets[c.id]*100)}%;background:${c.color}"></span></div></div><b>${Math.round(plan.spent[c.id]/plan.budgets[c.id]*100)}%</b></div>`).join('');renderCategories();save();
}
function renderCategories(){const list=activeCategories(categoryTab);$('#categoryList').innerHTML=list.length?list.map(c=>`<article class="budget-item category-item" data-edit-category="${c.id}"><div class="budget-row"><span class="budget-emoji" style="background:${c.color}22">${c.emoji}</span><div><div class="budget-name">${c.name}</div><div class="budget-numbers">${c.type==='expense'?'Расходы и планирование':'Доходы'}</div></div><span class="category-edit">Изменить ›</span></div></article>`).join(''):'<p class="hint">Категорий пока нет. Создайте первую кнопкой «+».</p>';document.querySelectorAll('[data-category-type]').forEach(b=>b.classList.toggle('selected',b.dataset.categoryType===categoryTab))}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.Telegram?.WebApp?.BackButton?.[id==='home'?'hide':'show']?.();window.scrollTo(0,0)}function closeModal(){document.querySelectorAll('.modal').forEach(x=>x.classList.remove('open'));$('#modalBackdrop').classList.remove('open');window.Telegram?.WebApp?.BackButton?.hide?.()}function openModal(id){closeModal();$('#'+id).classList.add('open');$('#modalBackdrop').classList.add('open');window.Telegram?.WebApp?.BackButton?.show?.()}
function fillCategories(select,type,selected){select.innerHTML=activeCategories(type).map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${c.emoji} ${c.name}</option>`).join('')}function fillGoals(select,selected){select.innerHTML=state.goals.map(g=>`<option value="${g.id}" ${String(g.id)===String(selected)?'selected':''}>${g.emoji||'🎯'} ${g.title}</option>`).join('')}
function openOperation(type,operation){const f=$('#operationForm');f.reset();$('#operationId').value=operation?.id||'';$('#operationType').value=type;const isGoal=type==='goal_deposit'||type==='goal_withdrawal';$('#operationTitle').textContent=operation?'Изменить операцию':type==='income'?'Новый доход':type==='expense'?'Новый расход':type==='goal_deposit'?'Пополнить цель':'Снять с цели';$('#operationTargetLabel').childNodes[0].textContent=isGoal?'Цель': 'Категория';if(isGoal)fillGoals($('#operationCategory'),operation?.goalId);else fillCategories($('#operationCategory'),type,operation?.category);const now=nowFields();$('#operationAmount').value=operation?.amount||'';$('#operationComment').value=operation?.comment||'';$('#operationDate').value=operation?.date||now.date;$('#operationTime').value=operation?.time||now.time;openModal('operationModal')}
function editBudget(id){const c=getCategory(id),plan=getPlan();$('#budgetId').value=c.id;$('#budgetModalTitle').textContent=`Бюджет: ${c.name}`;fillCategories($('#budgetCategory'),'expense',c.id);$('#budgetCategory').disabled=true;$('#budgetAmount').value=plan.budgets[c.id]||0;$('#removeBudget').hidden=false;openModal('budgetModal')}function editGoal(id){const g=getGoal(id);$('#goalModalTitle').textContent='Изменить цель';$('#goalId').value=g.id;$('#goalTitle').value=g.title;$('#goalDescription').value=g.description||'';$('#goalAmount').value=g.target;$('#goalCurrent').value=g.current;$('#goalCurrent').disabled=true;$('#goalDate').value=g.date||'';$('#deleteGoal').hidden=false;openModal('goalModal')}function editCategory(id){const c=getCategory(id);$('#categoryModalTitle').textContent='Изменить категорию';$('#categoryId').value=c.id;$('#categoryType').value=c.type;$('#categoryEmoji').value=c.emoji;$('#categoryName').value=c.name;$('#categoryColor').value=c.color||'#6756d9';$('#archiveCategory').hidden=false;openModal('categoryModal')}
function deleteOperation(id){const t=state.transactions.find(x=>String(x.id)===String(id));if(!t||!confirm(`Удалить операцию на ${money(t.amount)}?`))return;applyOperation(t,-1);state.transactions=state.transactions.filter(x=>String(x.id)!==String(id));render();haptic()}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)showScreen(go.dataset.go);const action=e.target.closest('[data-action]');if(action){const type=action.dataset.action;if(type==='goal'){$('#goalForm').reset();$('#goalId').value='';$('#goalCurrent').disabled=false;$('#goalModalTitle').textContent='Новая цель';$('#deleteGoal').hidden=true;openModal('goalModal')}else if(type==='plan')showScreen('plan');else if(type==='category'){$('#categoryForm').reset();$('#categoryId').value='';$('#categoryType').value=categoryTab;$('#categoryColor').value='#6756d9';$('#categoryModalTitle').textContent='Новая категория';$('#archiveCategory').hidden=true;openModal('categoryModal')}else openOperation(type)}if(e.target.closest('#addBudget')){$('#budgetForm').reset();$('#budgetId').value='';$('#budgetModalTitle').textContent='Распределить бюджет';fillCategories($('#budgetCategory'),'expense');$('#budgetCategory').disabled=false;$('#removeBudget').hidden=true;openModal('budgetModal')}if(e.target.closest('#editPlan')){$('#planIncome').value=getPlan().incomeTarget||availableNow();openModal('planModal')}if(e.target.closest('#prevPlanMonth')){const d=new Date(selectedPlanMonth+'-01T12:00:00');d.setMonth(d.getMonth()-1);selectedPlanMonth=monthKey(d);render()}if(e.target.closest('#nextPlanMonth')){const d=new Date(selectedPlanMonth+'-01T12:00:00');d.setMonth(d.getMonth()+1);selectedPlanMonth=monthKey(d);render()}const b=e.target.closest('[data-edit-budget]');if(b)editBudget(b.dataset.editBudget);const g=e.target.closest('[data-edit-goal]');if(g&&!e.target.closest('[data-goal-move]'))editGoal(g.dataset.editGoal);const move=e.target.closest('[data-goal-move]');if(move)openOperation(move.dataset.goalMove==='deposit'?'goal_deposit':'goal_withdrawal',{goalId:move.dataset.goalId});const c=e.target.closest('[data-edit-category]');if(c)editCategory(c.dataset.editCategory);const tab=e.target.closest('[data-category-type]');if(tab){categoryTab=tab.dataset.categoryType;renderCategories()}const edit=e.target.closest('[data-edit-operation]');if(edit){const t=state.transactions.find(x=>String(x.id)===String(edit.dataset.editOperation));if(t)openOperation(t.type,t)}const del=e.target.closest('[data-delete-transaction]');if(del)deleteOperation(del.dataset.deleteTransaction);if(e.target.closest('.close-modal')||e.target===$('#modalBackdrop'))closeModal()});
const today=nowFields();$('#todayLabel').textContent=new Date().toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();$('#operationDate').value=today.date;$('#operationTime').value=today.time;
$('#operationForm').addEventListener('submit',e=>{e.preventDefault();const oldId=$('#operationId').value,old=state.transactions.find(t=>String(t.id)===oldId),type=$('#operationType').value;const t={id:old?old.id:Date.now(),type,category:type==='goal_deposit'||type==='goal_withdrawal'?undefined:$('#operationCategory').value,goalId:type==='goal_deposit'||type==='goal_withdrawal'?$('#operationCategory').value:undefined,amount:Number($('#operationAmount').value),comment:$('#operationComment').value,date:$('#operationDate').value,time:$('#operationTime').value};if(old)applyOperation(old,-1);applyOperation(t,1);if(old)state.transactions=state.transactions.map(x=>String(x.id)===String(old.id)?t:x);else state.transactions.unshift(t);closeModal();render();haptic()});
$('#budgetForm').addEventListener('submit',e=>{e.preventDefault();const plan=getPlan(),id=$('#budgetCategory').value;plan.budgets[id]=Number($('#budgetAmount').value);plan.spent[id]??=0;closeModal();render();haptic()});$('#planForm').addEventListener('submit',e=>{e.preventDefault();getPlan().incomeTarget=Number($('#planIncome').value);closeModal();render();haptic()});
$('#goalForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#goalId').value,data={title:$('#goalTitle').value,description:$('#goalDescription').value,target:Number($('#goalAmount').value),date:$('#goalDate').value};if(id)Object.assign(getGoal(id),data);else{const goal={id:Date.now(),emoji:'🎯',current:Number($('#goalCurrent').value||0),...data};state.goals.unshift(goal);if(goal.current){const fields=nowFields(),t={id:Date.now()+1,type:'goal_deposit',goalId:goal.id,amount:goal.current,comment:'Первоначальное накопление',...fields};state.transactions.unshift(t)}}closeModal();render();haptic()});
$('#categoryForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#categoryId').value,data={type:$('#categoryType').value,emoji:$('#categoryEmoji').value,name:$('#categoryName').value,color:$('#categoryColor').value};if(id)Object.assign(getCategory(id),data);else state.categories.push({id:'cat-'+Date.now(),...data,spent:0,archived:false});closeModal();categoryTab=data.type;render();haptic()});$('#archiveCategory').addEventListener('click',()=>{const c=getCategory($('#categoryId').value);if(c){c.archived=true;closeModal();render();haptic()}});$('#removeBudget').addEventListener('click',()=>{const plan=getPlan(),id=$('#budgetId').value,c=getCategory(id);if(c&&confirm(`Убрать «${c.name}» из финансового плана?`)){delete plan.budgets[id];delete plan.spent[id];closeModal();render();haptic()}});$('#deleteGoal').addEventListener('click',()=>{const g=getGoal($('#goalId').value);if(g&&confirm(`Удалить цель «${g.title}»?`)){if(g.current){const fields=nowFields();state.transactions.unshift({id:Date.now(),type:'goal_withdrawal',goalId:g.id,amount:g.current,comment:'Закрытие цели',...fields})}state.goals=state.goals.filter(x=>x.id!==g.id);closeModal();render();haptic()}});window.showKopilkaScreen=showScreen;window.closeKopilkaModal=closeModal;render();hydrateRemote();
